#!/bin/bash
##################################################################################################
#
# Noxim - the NoC Simulator
#
# Copyright (C) 2005-2018 by the University of Catania
# For the complete list of authors refer to file ../../doc/AUTHORS.txt
# For the license applied to these sources refer to file ../../doc/LICENSE.txt
#
#*************************************************************************************************
# Downloaded March 23, 2022 from
# https://github.com/davidepatti/noxim/tree/c52ebce2217e57bcd4ff11a97b400323bd00acd5
#*************************************************************************************************
#
# NENoCSi: Patched version of Noxim to process traffic generated by NEST
# Modifications Copyright (C) 2023 Forschungszentrum Juelich GmbH, ZEA-2
# Author: Markus Robens <https://www.fz-juelich.de/profile/robens_m>
# For the license applied to these modifications and NENoCSi as a whole
# refer to file ../../doc/LICENSE_NENOCSI.txt
#  
# 2023-03-27: To large extents, this Bash script contains new commands to download and install
#             NEST as well as NENoCSi, if they are not already present. In addition, PyNEST's
#             cortical microcircuit model is copied to a convenient location, while two of its
#             Python scripts are modified to enable the generation of YAML files used for data
#             exchange between NEST and NENoCSi. Thus, it automates the streamlined procedure
#             proposed in ../../doc/INSTALL.txt. For more detailed information, please also
#             consult the documentation of the single simulators at
#             https://github.com/davidepatti/noxim/blob/master/doc/INSTALL.txt             and
#             https://nest-simulator.readthedocs.io/en/v3.1/installation/linux_install.html
#                                                                                                 
##################################################################################################
#
# Customization part
# ==================
#
# By default, this script will install the NEST-NENoCSi framework into the "nest-3.1" and
# "nenocsi-1.0" subfolders of your home directory. The build process and installation are only
# performed, if respective folders don't exist. This way, NEST-NENoCSi and NEST-McAERsim
# frameworks can be installed side-by-side.
#
# Set installation directories
INST_DIR=${HOME}
NEST_INST=${INST_DIR}/nest-3.1
#
# Automatically processed part - shouldn't be modified
# ====================================================
# Additional directories
NEST_BUILD=${INST_DIR}/nest-3.1-build
NEST_SRC=${HOME}/Downloads/nest-simulator-3.1
NEST_NENOCSI_ROOT=${INST_DIR}/nenocsi-1.0
#
# Get and build NEST if necessary
if ! [ -d ${NEST_INST} ]; then
    if ([ -d ${NEST_SRC} ] || [ -d ${NEST_BUILD} ]); then
	echo ""
	echo "Fragments of a former NEST installation still exist, can't proceed!"
	echo "You may want to delete them or install to a different directory."
	echo ""
	exit 1
    fi
echo ""
echo "Installing NEST 3.1 to ${NEST_INST}"
echo ""
cd ${NEST_SRC%/nest-simulator-3.1}
wget -O nest-simulator-3.1.tar.gz https://github.com/nest/nest-simulator/archive/refs/tags/v3.1.tar.gz
tar -xzf nest-simulator-3.1.tar.gz
# Configure and build NEST
PYVER=$(python3 -V | sed "s/^Python \([0-9]\.[0-9]\+\)\.[0-9]\+$/\1/")
mkdir ${NEST_INST}
mkdir ${NEST_BUILD}
cd ${NEST_BUILD}
cmake -DCMAKE_INSTALL_PREFIX:PATH=$NEST_INST -DCMAKE_BUILD_TYPE:STRING=Debug $NEST_SRC
make
export PYTHONPATH="${NEST_INST}/lib/python${PYVER}/site-packages${PYTHONPATH:+:$PYTHONPATH}"
make install
export PATH="${NEST_INST}/bin:${PATH}"
PYTHONUSERBASE=${NEST_INST} pip3 install --user junitparser
make installcheck
# Set additional NEST environment variable
cd ${NEST_INST}/bin
sed -i "\!export PATH=! a\\
\\
\# Set the location of user specific Python site-packages.\\
export PYTHONUSERBASE=\"${NEST_INST}\${PYTHONUSERBASE:+:\$PYTHONUSERBASE}\"
" nest_vars.sh
rm "${NEST_SRC}.tar.gz"
rm -r ${NEST_SRC}
rm -r ${NEST_BUILD}
fi
#
cd ${NEST_INST}/bin
source nest_vars.sh
# NENoCSi
if ! [ -d ${NEST_NENOCSI_ROOT} ]; then
echo ""
echo "Installing NENoCSi to ${NEST_NENOCSI_ROOT}"
echo ""
cd ${HOME}/Downloads
wget -O nenocsi-1.0.tar.gz https://github.com/mrobens/nenocsi-mcaersim/archive/refs/tags/nenocsi-1.0.tar.gz
# Extract and build NENoCSi
mkdir ${NEST_NENOCSI_ROOT}
cd ${NEST_NENOCSI_ROOT}
tar --strip-components=1 -xzf ${HOME}/Downloads/nenocsi-1.0.tar.gz
cd bin
make depend
make
cd ${NEST_NENOCSI_ROOT}/nest_inputs
cp ${NEST_INST}/share/doc/nest/examples/pynest/Potjans_2014/*.py .
sed -i "\!import warnings! a\\
import helpers_aux
\!helpers\.boxplot(self\.data_path, self\.net_dict\['populations'\])! a\\
            if(self.sim_dict['gen_yaml']):\\
                print('Exporting to ' + self.sim_dict['exp_name'] + '_NpN_'\\
                      + str(self.sim_dict['hw_node_sz']) + '.yaml')\\
                helpers_aux.Export_Spikes_and_Targets(self.data_path, 'spike_recorder',\\
                                                      self.sim_dict['exp_name'], self.pops,\\
                                                      self.num_neurons,\\
                                                      self.sim_dict['hw_node_sz'],\\
                                                      self.sim_dict['t_presim'],\\
                                                      self.sim_dict['t_presim']\\
                                                      + self.sim_dict['t_sim'])
" network.py
sed -i "\!sim_dict = {! a\\
    \# Select if YAML output is created or not\\
    \# This step is time consuming. Progress is indicated by greater symbols.\\
    'gen_yaml': True,\\
    \# Basic name of the YAML file used for data export\\
    'exp_name': 'Nest_MicroCirc_SpkTimes',\\
    \# Number of neurons that can be hosted on a hardware node\\
    'hw_node_sz': 256,
" sim_params.py
python3 run_microcircuit.py
rm ${HOME}/Downloads/nenocsi-1.0.tar.gz
cd ${NEST_NENOCSI_ROOT}/scripts
chmod u+x aux_scripts/*.sh
chmod u+x *.sh
fi
cd ${NEST_NENOCSI_ROOT}/scripts
