/*
 * Noxim - the NoC Simulator
 *
 * (C) 2005-2018 by the University of Catania
 * For the complete list of authors refer to file ../../doc/AUTHORS.txt
 * For the license applied to these sources refer to file ../../doc/LICENSE.txt
 */
/*\\\********************************************************************************
 * Downloaded March 23, 2022 from
 * https://github.com/davidepatti/noxim/tree/c52ebce2217e57bcd4ff11a97b400323bd00acd5
 ************************************************************************************
 *
 * NENoCSi: Patched version of Noxim to process traffic generated by NEST
 * Author: Markus Robens <https://www.fz-juelich.de/profile/robens_m>
 * For the license applied to modifications and NENoCSi as a whole
 * refer to file ../../doc/LICENSE_NENOCSI.txt
 * 
 * This file was modified on April 20, 2022 to enable XY routing in torus
 * shaped networks.
 *
 *///******************************************************************************** 
#ifndef __NENOCSIROUTING_XY_TORUS_H__
#define __NENOCSIROUTING_XY_TORUS_H__

#include "RoutingAlgorithm.h"
#include "RoutingAlgorithms.h"
#include "../Router.h"

using namespace std;

class Routing_XY_TORUS : RoutingAlgorithm {
	public:
		vector<int> route(Router * router, const RouteData & routeData);

		static Routing_XY_TORUS * getInstance();

	private:
		Routing_XY_TORUS(){};
		~Routing_XY_TORUS(){};

		static Routing_XY_TORUS * routing_XY_TORUS;
		static RoutingAlgorithmsRegister routingAlgorithmsRegister;
};

#endif
