#!/bin/bash
#**************************************************************************************
#                                                                                      
# McAERsim-Framework: Network traffic within McAERsim generated by NEST
# Copyright (C) 2022-2023 Forschungszentrum Juelich GmbH, ZEA-2                        
# Author: Markus Robens <https://www.fz-juelich.de/profile/robens_m>                   
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#************************************************************************************
#                                                                                      
# This shell script applies to the torus topology and multicast routing. It iterates
# through different acceleration factors and uses the command line interface of
# McAERsim in order to override the default settings read from the configuration file
# config.yaml. It calls one to two additional shell scripts for evaluation and figure
# creation purposes. Look at these files for more information. Figures are only
# created, if DO_PLOTTING is set to true. 
#                                                                                      
#**************************************************************************************
DO_PLOTTING=1
SIM_TIME=1400000000
TIME_MUL=1000000000
TOPOLOGY="torus"
DIM="6x6"
cd ../bin
BINDIR=$(pwd)
mkdir data
DIMX=$(echo ${DIM} | sed "s/\([0-9]*\)x[0-9]*/\1/")
DIMY=$(echo ${DIM} | sed "s/[0-9]*x\([0-9]*\)/\1/")
for ACC in 1 2 5 10 20 50 100 200 500
do
    printf -v OFNAME "data/${TOPOLOGY}_${DIM}_256_npn_MC_acc_%03d.txt" $ACC
    printf -v SUFFIX "_${TOPOLOGY}_${DIM}_256_npn_MC_acc_%03d" $ACC
    ./mcaersim -config config.yaml -topology ${TOPOLOGY^^?} -sim $(( $SIM_TIME / $ACC ))\
	    -dimX ${DIMX} -dimY ${DIMY} -verbose "VERBOSE_LOW"\
	    -rt_file "../nest_inputs/data/NEST_MC_Global_RT_${TOPOLOGY^?}.yaml"\
	    -nest_t_mul $(( $TIME_MUL / $ACC )) -of_suffix $SUFFIX > $OFNAME 2>&1
done
../scripts/aux_scripts/eval_acc_factor_sweep.sh ${BINDIR} ${TOPOLOGY} ${DIM}
mkdir data/Delays
mkdir data/Evts_Routed
mv data/Delays_*.csv data/Delays
mv data/Evts_Routed_*.csv data/Evts_Routed
mv data data_${TOPOLOGY}_MC
mkdir -p results
mv data_${TOPOLOGY}_MC results
if (( $DO_PLOTTING==1 ))
then
    ../scripts/aux_scripts/eval_plots.sh ${BINDIR} ${TOPOLOGY} ${DIM}
fi

