#!/bin/bash
#**************************************************************************************
#                                                                                      
# NENoCSi-Framework: Network traffic within NENoCSi generated by NEST
# Copyright (C) 2022-2023 Forschungszentrum Juelich GmbH, ZEA-2                        
# Author: Markus Robens <https://www.fz-juelich.de/profile/robens_m>                   
#                                                                                      
# This program is free software: you can redistribute it and/or modify                 
# it under the terms of the GNU General Public License as published by                 
# the Free Software Foundation, either version 3 of the License, or                    
# (at your option) any later version.                                                  
#                                                                                      
# This program is distributed in the hope that it will be useful,                      
# but WITHOUT ANY WARRANTY; without even the implied warranty of                       
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                        
# GNU General Public License for more details.                                         
#                                                                                      
# You should have received a copy of the GNU General Public License                    
# along with this program.  If not, see <https://www.gnu.org/licenses/>.               
#                                                                                      
#**************************************************************************************
#                                                                                      
# This shell script applies to the mesh toplogy and destination-address driven unicast 
# routing. It iterates through different acceleration factors and uses the command     
# line interface of NENoCSi in order to override the default settings read from the
# configuration file config.yaml. It calls one to two additional shell scripts for
# evaluation and figure creation purposes. Look at these files for more information.
# Figures are only created, if DO_PLOTTING is set to true. 
#                                                                                      
#**************************************************************************************
DO_PLOTTING=1
SIM_TIME=1400000000
TIME_MUL=1000000000
TOPOLOGY="mesh"
CASTING="UC"
cd ../bin
BINDIR=$(pwd)
mkdir data
for ACC in 1 2 5 10 20 50 100 200 500
do
    printf -v OFNAME "data/${TOPOLOGY}_6x6_256_npn_${CASTING}_acc_%03d.txt" $ACC
    printf -v SUFFIX "_${TOPOLOGY}_6x6_256_npn_${CASTING}_acc_%03d" $ACC
    ./nenocsi -config config.yaml -topology ${TOPOLOGY^^?} -sim $(( $SIM_TIME / $ACC ))\
	      -nest_t_mul $(( $TIME_MUL / $ACC )) -casting_type ${CASTING}\
	      -size 1 1 -ofile_suffix $SUFFIX > $OFNAME 2>&1
done
../scripts/aux_scripts/eval_acc_factor_sweep.sh ${BINDIR} ${TOPOLOGY} ${CASTING}
mkdir data/Delays
mkdir data/Flits_Routed
mv data/Delays_*.csv data/Delays
mv data/Flits_Routed_*.csv data/Flits_Routed
mv data data_${TOPOLOGY}_${CASTING}
mkdir -p results
mv data_${TOPOLOGY}_${CASTING} results
if (( $DO_PLOTTING==1 ))
then
    ../scripts/aux_scripts/eval_plots.sh ${BINDIR} ${TOPOLOGY} ${CASTING}
fi

